extends: incuna

env:
  node: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
    modules: true

rules:
  prefer-const: error
  object-curly-newline:
    - error
    -
      ObjectExpression:
        minProperties: 3
        multiline: true
        consistent: true
      ObjectPattern:
        multiline: true
        consistent: true
